image: maven:3.8.3-openjdk-17

stages:
    - build
    - test

build: 
    stage: build
    script:
        - mvn -DskipTests=true clean install
        
test:
    stage: test
    script: 
        - mvn test
