name: Java CI with Maven

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn package "-Dfile=cobra.jar" "-DgroupId=com.example.MoveFreeBackend" "-DartifactId=movefreebackend" "-Dversion=0.98.4" "-Dpackaging=jar" "-DgeneratePom=true"

      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: MoveFreeBackend
          path: target/MoveFreeBackend-0.0.1-SNAPSHOT.jar
